Math magicians: components
bill7pearl/math-magician pull request #2
Opened 2023-01-19 14:16 UTC by bill7pearl

# In this PR I have:
- Deleted all the boilerplate from CRA (text, images, styles).
- Created a directory called components.
- Inside components, created a new Calculator.js file.
- In Calculator.js, created a React component that matches the design provided.

2023-01-19 14:20 UTC, TedLivist commented
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @bill7pearl,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### 1. Kindly fix your linter error.
### 2. Kindly ensure you format your README using [the Microverse template](https://github.com/microverseinc/readme-template). All table of contents should be present and working correctly

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-19 14:48 UTC, Deepakdanger requested changes
Hi @bill7pearl  

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
- [ ] The button `0` is twice in length, kindly change it according to the original design.
- your design


![Screenshot from 2023-01-19 20-06-25](https://user-images.githubusercontent.com/26767383/213472615-267ebff8-dd52-4ffa-867e-4976616eeab7.png)


- Original design
![Screenshot from 2022-11-10 00-26-21](https://user-images.githubusercontent.com/26767383/213472589-3e6911f8-877f-4755-a0d4-bc5e20297e14.png)





- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Kindly use the same color as `=` button as in the original design, after approval you can advance your design calculator in various ways.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 14:48 UTC, Deepakdanger commented on src/components/Wrapper.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-19 14:48 UTC, Deepakdanger commented on src/components/CalcContext.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-19 14:48 UTC, Deepakdanger commented on src/components/ButtonBox.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-19 14:48 UTC, Deepakdanger commented on src/components/Button.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-19 14:48 UTC, Deepakdanger commented on src/App.js
> +/* eslint-disable import/no-extraneous-dependencies */
- [ ] Kindly remove it & solve it manually

2023-01-19 19:40 UTC, alexander16108 requested changes
Hi @bill7pearl , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/vyTnNTrs3wqQ0UIvwE/giphy.gif"/>

 ## Highlights

- No linter error ✔️
- Website looks professional 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 19:40 UTC, alexander16108 commented on src/App.js
> +/* eslint-disable import/no-extraneous-dependencies */
- [ ]  Kindly remove it & solve it manually

2023-01-19 19:40 UTC, alexander16108 commented on src/components/Button.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-19 19:40 UTC, alexander16108 commented on src/components/ButtonBox.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-19 19:40 UTC, alexander16108 commented on src/components/CalcContext.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-19 19:40 UTC, alexander16108 commented on src/components/Wrapper.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly remove it & solve it manually

2023-01-21 11:23 UTC, AnselemOdims approved these changes
### Hi  @bill7pearl 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 11:58 UTC, merged